version: "3.8"
services:
  bootnode:
    image: ghcr.io/wuzhanfly/bpc-template-bsc-v2:latest
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--networkid=${CHAIN_ID}"
      - "--nodekey=/datadir/bootnodes.key"
      - "--syncmode=full"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/bootnode:/datadir/geth"
      - "./config/bootnodes.key:/datadir/bootnodes.key"
    ports:
      - "30303:30303"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size
