version: "3.8"
services:
  bootnode:
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--networkid=${CHAIN_ID}"
      - "--nodekey=/datadir/bootnodes.key"
      - "--blspassword=/datadir/password.txt"
      - "--verbosity=4"
      - "--syncmode=full"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/bootnode:/datadir/geth"
      - "./config/password.txt:/datadir/password.txt"
      - "./config/bootnodes.key:/datadir/bootnodes.key"
      - "./config/bls/data55/bls:/datadir/bls"
    ports:
      - "30303:30303"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_1:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x73a8bceFA940Cefbf4cADB9fa79c30Ac283BA867"
      - "--miner.etherbase=0x73a8bceFA940Cefbf4cADB9fa79c30Ac283BA867"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--verbosity=4"
      - "--syncmode=full"
      - "--networkid=${CHAIN_ID}"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data1/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_1:/datadir/geth"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_2:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x345D31A29dE1f8388EA7954f0dDF73782a9caD08"
      - "--miner.etherbase=0x345D31A29dE1f8388EA7954f0dDF73782a9caD08"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--verbosity=4"
      - "--syncmode=full"
      - "--networkid=${CHAIN_ID}"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data2/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_2:/datadir/geth"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_3:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x378E1761be54ab6545e6563d1b59b424D3eE31A5"
      - "--miner.etherbase=0x378E1761be54ab6545e6563d1b59b424D3eE31A5"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data3/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_3:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_4:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x000E0883978b34302EF7359cB480299767EE36a2"
      - "--miner.etherbase=0x000E0883978b34302EF7359cB480299767EE36a2"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data4/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_4:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_5:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xC359Fe96EfD30F289608804DDDFd46EB14162430"
      - "--miner.etherbase=0xC359Fe96EfD30F289608804DDDFd46EB14162430"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/bls/data5/bls:/datadir/bls"
      - "./config/keystore:/datadir/keystore"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_5:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_6:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x930B166e73B4B5f93299D3E4739F9a1dc92a8407"
      - "--miner.etherbase=0x930B166e73B4B5f93299D3E4739F9a1dc92a8407"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data6/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_6:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_7:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x1Edb50507114Cfb3D082d55fDfA6FDcFF4EDa591"
      - "--miner.etherbase=0x1Edb50507114Cfb3D082d55fDfA6FDcFF4EDa591"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data7/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_7:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_8:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xB38eA6371499c1B364C61bF15404760374962339"
      - "--miner.etherbase=0xB38eA6371499c1B364C61bF15404760374962339"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data8/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_8:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_9:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xe1b34f145262c06e74a58c111CDbC148753BBcC1"
      - "--miner.etherbase=0xe1b34f145262c06e74a58c111CDbC148753BBcC1"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data9/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_9:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_10:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xF016A30Aeb1AaFa2EB4b2deBf981a153246C9507"
      - "--miner.etherbase=0xF016A30Aeb1AaFa2EB4b2deBf981a153246C9507"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data10/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_10:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_11:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x69C1E8b33254BEaf4BBc35EA49206b24172341bE"
      - "--miner.etherbase=0x69C1E8b33254BEaf4BBc35EA49206b24172341bE"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data11/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_11:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_12:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xa8fd80cA9D309a7dd34785975cF03de1F9D85C5B"
      - "--miner.etherbase=0xa8fd80cA9D309a7dd34785975cF03de1F9D85C5B"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data12/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_12:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size

  validator_13:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--blspassword=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x3D97A28C98B5fb50B4FaeC70F98597513929C0a6"
      - "--miner.etherbase=0x3D97A28C98B5fb50B4FaeC70F98597513929C0a6"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--networkid=${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/bls/data13/bls:/datadir/bls"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_13:/datadir/geth"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size
  rpc:
    depends_on:
      - bootnode
    image: ghcr.io/wuzhanfly/bpc-v3:dev
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--networkid=${CHAIN_ID}"
      - "--blspassword=/datadir/password.txt"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--verbosity=4"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,trace,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "10545:8545"
      - "10546:8546"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/rpc:/datadir/geth"
      - "./config/bls/data54/bls:/datadir/bls"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size
