version: "3.8"
services:
  validator_add:
    image: ghcr.io/wuzhanfly/bpc-genesis-config-v2:latest
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xD0F5B2251A17c41ffD7152Dae5ff846075F49E63"
      - "--miner.etherbase=0xD0F5B2251A17c41ffD7152Dae5ff846075F49E63"
      - "--bootnodes=enode://4878ee78197d7f710c172095b7ebc13a99a157e8614007f615f4eb0085a9ad42731347f618f40b8ca9d1a7c1f9519407f184cd4fd03e23de0d54222d19dd8f67@host.docker.internal:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=${CHAIN_ID}"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./config/keystore:/datadir/keystore"
      - "./config/password.txt:/datadir/password.txt"
      - "./datadir/validator_add:/datadir/geth"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size